export * from "./admin";
export * from "./assignment";
export * from "./attendance";
export * from "./auth";
export * from "./client";
export * from "./course";
export * from "./exam";
export * from "./student";
export * from "./teacher";
